version: "2.4"
services:
  redis:
    image: mariadb
    container_name: mariadb
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=test123
