version: "2.4"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379
    restart: unless-stopped
  postgre:
    image: postgres
    container_name: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: test
    restart: unless-stopped